name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
    tags:

jobs:
  matrix:
    name: Generate job matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Gather CI configuration
        id: matrix
        uses: laminas/laminas-ci-matrix-action@b08a9a088a397b72af093f865e1f67f9e5072867 # 1.27.2

  qa:
    name: QA Checks
    needs: [matrix]
    runs-on: ${{ matrix.operatingSystem }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
      - name: ${{ matrix.name }}
        uses: laminas/laminas-continuous-integration-action@f474cab0f489b50c3b31d6ae04f0a5fc189c796d # 1.40.0
        with:
          job: ${{ matrix.job }}
    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211

      mongodb:
        image: mongo
        ports:
          - 27017:27017

      rabbitmq:
        image: rabbitmq
        ports:
          - 5672:5672

      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
